stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: webofmars/sample-nodejs
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: '#monitoring'
    notifier: c-sfqsc:n-b2z42
  condition:
  - Success
  - Changed
  - Failed
